name:  Deploy

on:
  pull_request:
    types: 
      - closed
    branches:
      - develop
      - main
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches: 
      - "feature/*"
      - develop
      - "release*"
jobs:
  build-feature: 
   name: Build project
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [16.x]
   steps:
      - run: echo build project
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Print info
        run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"
  deploy-dev: 
   name: Deploy to dev
   needs: build-feature 
   if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/')
   runs-on: ubuntu-latest
   steps:
      - run: echo build feature
      - name: Print info
        run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"
      - run: echo Deploy to dev