pull_request:
    types: 
      - closed
    branches:
      - develop
  push:
    branches: [ main, feature ]

jobs:
  deploy-dev: 
   name: Deploy to dev
   if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/')
   runs-on: ubuntu-latest
   steps:
      - run: echo build feature 
     
  deploy-testing:
    name: Deploy to testing
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'develop')
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to testing 