name:  Deploy

on:
  pull_request:
    types: 
      - closed
    branches:
      - develop
  push:
    branches: 
      - "feature/*"

jobs:
  build-feature: 
   name: Build feature
   runs-on: ubuntu-latest
   steps:
      - run: echo build feature