name:  Deploy

on:
  pull_request:
    types: 
      - closed
    branches:
      - develop
      - main
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches: 
      - "feature/*"
      - develop
      - "release*"
jobs:
  checkout-code: 
   name: Checkout code 
   runs-on: ubuntu-latest
   steps:
      - run: echo "Checkout '${{ github.ref_name }}' pushed by '${{ github.event.pusher.name }}'" 
      - uses: actions/checkout@v2
  build-project: 
   name: Build project
   needs: checkout-code
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [16.x]
   steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Print info
        run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"