pull_request:
    types: 
      - closed
    branches:
      - develop
  push:
    branches: [ feature ]

jobs:
  build-feature: 
   name: Build feature
   if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/')
   runs-on: ubuntu-latest
   steps:
      - run: echo build feature 
