name:  Deploy

on:
  pull_request:
    types: 
      - closed
    branches:
      - develop
  push:
    branches: 
      - "feature/*"

jobs:
  build-feature: 
   name: Build feature
   if: startsWith( github.ref_name, 'test')
   runs-on: ubuntu-latest
   steps:
      - run: echo build feature
      - name: Print info
        run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"