
name: Continuous Integration for Develpment (CI)

on:
  pull_request:
    types: 
      - closed
    branches:
      - develop
  push:
    branches:
      #- main
      - "feature/*"
      #- develop
      
jobs:
  build-project:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest
    steps:
     - name: Checking out project from ${{ github.ref_name }} for the event ${{ github.event_name }}
       uses: actions/checkout@v2
     - name: Setup node version ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
          node-version: 16
     - name: Cache node modules
       id: cache-npm
       uses: actions/cache@v3
       env:
         cache-name: cache-node-modules
       with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

     - name: Running node continuous integration
       run: npm ci
     - name: Building node 
       run: npm run build --if-present     
     
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting source code 
        uses: github/super-linter@v3.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.ref_name }}

  check-project:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build-project
    runs-on: ubuntu-latest
    steps:
     - name: Validating project from ${{ github.head_ref }} #${{ github.base_ref }} ${{ github.head_ref }}
       run: echo validating del proyecto
     #- run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"
     #- run: echo " run number '${{ github.run_number }}' "  
     #- run: echo " event name '${{ github.event_name }}' " 
     #- run: echo " base ref '${{ github.base_ref }}' " 
     #- run: echo " head ref '${{ github.head_ref }}' " 
  deploy-project:
    needs: check-project
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      stage: dev
  #  secrets:
  #    AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  #    AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  #deploy-project:
  #  needs: check-project
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Deploy project from ${{ github.head_ref }} to DEV ${{ github.base_ref }} ${{ github.head_ref }}
  #     run: echo Deploy del proyecto 
     