name: Continuous Integration for Release (CI)
on:
  pull_request:
    types: 
      - closed
    branches:
      - main
  push:
    branches:
      #- main
      - "release*"
      #- develop 
jobs:
  build-project:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest
    steps:
     - name: Checking out project from ${{ github.ref_name }} for the event ${{ github.event_name }}
       uses: actions/checkout@v2
     - name: Setup node version ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
          node-version: 16
     - name: Cache node modules
       id: cache-npm
       uses: actions/cache@v3
       env:
         cache-name: cache-node-modules
       with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

     - name: Running node continuous integration
       run: npm ci
     - name: Building node 
       run: npm run build --if-present     
     - name: Linting source code 
       run: npm run lint

  check-project:
    if: ${{ github.event_name == 'push' }} || ${{ github.event_name == 'pull_request' }}
    needs: build-project
    runs-on: ubuntu-latest
    steps:
     - name: Validating project from ${{ github.head_ref }} #${{ github.base_ref }} ${{ github.head_ref }}
       run: echo validating del proyecto
     #- run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"
     #- run: echo " run number '${{ github.run_number }}' "  
     #- run: echo " event name '${{ github.event_name }}' " 
     #- run: echo " base ref '${{ github.base_ref }}' " 
     #- run: echo " head ref '${{ github.head_ref }}' " 
  
  generate-release:
    if: ${{ github.event_name == 'push' }}
    needs: check-project
    runs-on: ubuntu-latest
    steps:
     - name: Generate release of project from ${{ github.head_ref }} #${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Generate proyect release
 
  deploy-release:
    if: ${{ github.event_name == 'push' }}
    needs: generate-release
    runs-on: ubuntu-latest
    steps:
     - name: Deploy release of project from ${{ github.head_ref }} #${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy proyect release
  
  deploy-project:
    if: ${{ github.event_name == 'pull_request' }}
    needs: check-project
    runs-on: ubuntu-latest
    steps:
     - name: Deploy project from ${{ github.head_ref }} to PRO ${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy del proyecto 
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    needs: deploy-project
    runs-on: ubuntu-latest
    steps: 
     - name: Merge from ${{ github.head_ref }} #${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy proyect release
     - uses: actions/checkout@v2
     - name: Set Git config
       run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
     - name: Merge master back to dev
       run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff origin/main -m "Auto-merge master back to dev"
          git push     