name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
      - "feature/*"
      - develop
      
jobs:
  build:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest
    
    steps:
     - name: build project
       run: echo build project