name: Continuous Integration (CI)

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      #- main
      - "feature/*"
      #- develop
      
jobs:
  build-project:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest
    steps:
     - name: Checking out project from ${{ github.ref_name }}
       uses: actions/checkout@v2
     - name: Setup node version ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
          node-version: 16
     - name: Cache node modules
       id: cache-npm
       uses: actions/cache@v3
       env:
         cache-name: cache-node-modules
       with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

     - name: Running node continuous integration
       run: npm ci
     - name: Building node 
       run: npm run build --if-present     
     - name: Linting source code 
       run: npm run lint
  check-project:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build-project
    runs-on: ubuntu-latest
    steps:
     - name: Checking out project from ${{ github.ref_name }} ${{ github.base_ref }} ${{ github.head_ref }}
       run: echo check del proyecto
     #- run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"
     #- run: echo " run number '${{ github.run_number }}' "  
     #- run: echo " event name '${{ github.event_name }}' " 
     #- run: echo " base ref '${{ github.base_ref }}' " 
     #- run: echo " head ref '${{ github.head_ref }}' " 
  deploy-project:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
     - name: Deploy project from ${{ github.ref_name }} ${{ github.base_ref }} ${{ github.head_ref }}
       run: echo Deploy del proyecto 
     