name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
      - "feature/*"
      - develop
      
jobs:
  build:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest
    
    steps:
     - name: build project
       run: echo build project
     - run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"
     - run: echo " run number '${{ github.run_number }}' "  
     - run: echo " event name '${{ github.event_name }}' " 
     - run: echo " base ref '${{ github.base_ref }}' " 
     - run: echo " head ref '${{ github.head_ref }}' " 

     